import React, { useState } from 'react';
import './App.css';

// import logoImg from './assets/logo-small.png';
import mascotImg from './assets/fish.png';
// import starsImg from './assets/stars.png';
// import igIcon from './assets/ig.png';
// import fbIcon from './assets/fb.png';
// import tiktokIcon from './assets/tiktok.png';

function App() {
  // App States: 'input', 'loading', 'results'
  const [appState, setAppState] = useState('input');
  const [repoUrl, setRepoUrl] = useState('');
  const [progress, setProgress] = useState(0);

  // Data generated by the AI
  const [reportData, setReportData] = useState({
    grade: '',
    cardText1: '',
    cardText2: '',
    cardText3: '',
    summaryText: ''
  });

  // COLLABORATORS: Hook up Tiny Fish & OpenAI here!
  const runJudgement = async (e) => {
    e.preventDefault();
    if (!repoUrl) return;

    setAppState('loading');
    setProgress(0);

    // --- MOCK LOADING SIMULATION ---
    // Remove this setInterval when hooking up the real backend.
    // Instead, update progress based on scraper/API milestones.
    const interval = setInterval(() => {
      setProgress((prev) => {
        if (prev >= 100) {
          clearInterval(interval);
          return 100;
        }
        return prev + 10;
      });
    }, 400);

    try {
      // 1. Run Tiny Fish Scraper
      // const scrapedData = await runTinyFish(repoUrl);
      
      // 2. Pass to OpenAI
      // const aiResponse = await getOpenAILogic(scrapedData);

      // 3. Wait for progress bar to finish (for UX smoothness)
      await new Promise(resolve => setTimeout(resolve, 4500)); 

      // 4. Set the Result State with actual AI data
      setReportData({
        grade: 'C+',
        cardText1: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        cardText2: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        cardText3: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        summaryText: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s..."
      });

      setAppState('results');
    } catch (error) {
      console.error("Error scraping or generating data:", error);
      alert("Failed to judge your repo. Even the AI gave up.");
      setAppState('input');
    }
  };

  return (
    <div className="app-container">
      {/* HEADER */}
      <header className="header">
        <img src={mascotImg} alt="NotFreshEnough logo" className="header-logo" />
        <h1>NotFreshEnough</h1>
      </header>

      {/* INPUT & LOADING SCREEN (Matches Image 1) */}
      {(appState === 'input' || appState === 'loading') && (
        <main>
          <div className="two-column-layout">
            <div className="left-col">
              <h2 className="submit-title"><span>Submit</span> for Judgement</h2>
              <p className="intro-text">
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
              </p>
              
              <form className="input-group" onSubmit={runJudgement}>
                <input 
                  type="text" 
                  className="repo-input"
                  placeholder="Paste your Github Repo here" 
                  value={repoUrl}
                  onChange={(e) => setRepoUrl(e.target.value)}
                  disabled={appState === 'loading'}
                />
                <button type="submit" className="submit-btn" disabled={appState === 'loading'}>
                  {/* CSS Mouse cursor icon placeholder */}
                  <span>🖱️</span> 
                </button>
              </form>
            </div>

            <div className="right-col">
              <img src={mascotImg} alt="NotFreshEnough mascot" className="mascot-img" />
            </div>
          </div>

          {/* LOADING BAR (Only shows when loading) */}
          {appState === 'loading' && (
            <div className="loading-container">
              {/* Replace with stars image */}
              <div className="stars-icon" style={{ fontSize: '3rem', color: '#a020f0' }}>✨</div>
              <div className="progress-wrapper">
                <p>Generating...</p>
                <div className="progress-bar-container">
                  <div 
                    className="progress-bar-fill" 
                    style={{ width: `${progress}%` }}
                  ></div>
                </div>
              </div>
            </div>
          )}
        </main>
      )}

      {/* RESULTS SCREEN (Matches Image 2) */}
      {appState === 'results' && (
        <main className="results-container">
          <div className="left-col">
            {/* The Report Card Visual */}
            <div className="report-card-visual">
              <h2>REPORT CARD</h2>
              <h2 className="grade-text">OVERALL GRADE: {reportData.grade}</h2>
              
              <div className="box-text">{reportData.cardText1}</div>
              <div className="box-text">{reportData.cardText2}</div>
              <div className="box-text">{reportData.cardText3}</div>
            </div>
          </div>

          <div className="results-text-col right-col">
            <h2>REPORT CARD<br/><span className="grade-text">OVERALL GRADE: {reportData.grade}</span></h2>
            
            <p className="results-description">
              {reportData.summaryText}
            </p>
            <p className="results-description">
              {reportData.summaryText}
            </p>

            <p className="disappointment-text">You disappointed your family.</p>
            <button className="fail-btn">FAIL</button>
          </div>
        </main>
      )}

      {/* FOOTER (Only shows on Results screen based on mockup, but you can move it outside the condition if you want it always) */}
      {appState === 'results' && (
        <footer className="footer">
          <span>Share your Shame</span>
          <div className="social-icons">
            {/* Replace with actual icons */}
            <span style={{ fontSize: '24px', cursor: 'pointer' }}>📸</span>
            <span style={{ fontSize: '24px', cursor: 'pointer' }}>📘</span>
            <span style={{ fontSize: '24px', cursor: 'pointer' }}>🎵</span>
          </div>
        </footer>
      )}
    </div>
  );
}

export default App;
